//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.07 at 10:48:30 AM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.citizen.soap.soapdemo.webservices.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.webservices.soapdemo.soap.citizen;
